#!/usr/bin/env bash

selected=$(find ~/cod ~/.config ~/cod/projects -mindepth 1 -maxdepth 3 -type d | fzf)

if [[ -n $selected ]]; then
    cd "$selected"
    if [ -e "Session.vim" ]; then
        v -S Session.vim
    else
        v .
    fi
fi
